[versions]
rxJava = "2.2.19"
kotlin-coroutine = "1.4.3"

[libraries]
rxJava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxJava"}
kotlin-coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutine" }

[bundles]
